export const listSeeds = [
  {
    listName: "Baking Bread",
    color: "#f8b400",
    userName: "Alice Johnson",
    global: true,
    ratings: 4,
  },
  {
    listName: "Plan Trip to NY",
    color: "#00a2ff",
    userName: "Bob Smith",
    global: true,
    ratings: 5,
  },
  {
    listName: "Picnic in a Park",
    color: "#3cb371",
    userName: "Carol White",
    global: true,
    ratings: 3,
  },
  {
    listName: "Mari Kondo My Home",
    color: "#ff6347",
    userName: "David Lee",
    global: true,
    ratings: 5,
  },
  {
    listName: "Sleep Routine Backed by Science",
    color: "#6a5acd",
    userName: "Eva Brown",
    global: true,
    ratings: 5,
  },
  {
    listName: "Job Interview Preparation",
    color: "#ff4500",
    userName: "Frank Wright",
    global: true,
    ratings: 2,
  },
  {
    listName: "Lord of the Rings Marathon Party",
    color: "#daa520",
    userName: "Alice Johnson",
    global: true,
    ratings: 3,
  },
  {
    listName: "Grocery List for a BBQ",
    color: "#f08080",
    userName: "David Lee",
    global: true,
    ratings: 3,
  },
  {
    listName: "Movies to Watch",
    color: "#20b2aa",
    userName: "Grace Hall",
    global: true,
    ratings: 3,
  },
  {
    listName: "React Hooks Study Session",
    color: "#4682b4",
    userName: "Bob Smith",
    global: true,
    ratings: 5,
  },
];
