[
  {
    listName: "Baking Bread",
    color: "#f8b400",
    user: "Alice Johnson",
    sharedUsers: ["Bob Smith", " Carol White"],
    global: true,
    ratings: 4,
  },
  {
    listName: "Plan Trip to NY",
    color: "#00a2ff",
    user: "Bob Smith",
    sharedUsers: ["Alice Johnson", " Eva Brown"],
    global: true,
    ratings: 5,
  },
  {
    listName: "Picnic in a Park",
    color: "#3cb371",
    user: "Carol White",
    sharedUsers: ["David Lee", " Grace Hall"],
    global: true,
    ratings: 3,
  },
  {
    listName: "Mari Kondo My Home",
    color: "#ff6347",
    user: "David Lee",
    sharedUsers: ["Eva Brown", " Frank Wright"],
    global: true,
    ratings: 5,
  },
  {
    listName: "Sleep Routine Backed by Science",
    color: "#6a5acd",
    user: "Eva Brown",
    sharedUsers: ["Carol White", " Grace Hall"],
    global: true,
    ratings: 5,
  },
  {
    listName: "Job Interview Preparation",
    color: "#ff4500",
    user: "Frank Wright",
    sharedUsers: ["Bob Smith", " David Lee"],
    global: true,
    ratings: 2,
  },
  {
    listName: "Lord of the Rings Marathon Party",
    color: "#daa520",
    user: "Alice Johnson",
    sharedUsers: ["Frank Wright", " Grace Hall"],
    global: true,
    ratings: 3,
  },
  {
    listName: "Grocery List for a BBQ",
    color: "#f08080",
    user: "David Lee",
    sharedUsers: ["Alice Johnson", " Bob Smith"],
    global: true,
    ratings: 3,
  },
  {
    listName: "Movies to Watch",
    color: "#20b2aa",
    user: "Grace Hall",
    sharedUsers: ["Eva Brown", " Carol White"],
    global: true,
    ratings: 3,
  },
  {
    listName: "React Hooks Study Session",
    color: "#4682b4",
    user: "Bob Smith",
    sharedUsers: ["David Lee", " Frank Wright"],
    global: true,
    ratings: 5,
  },
];
