[
  {
    id: null,
    listID: null,
    description: "Feed sourdough night before",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Prepare starter for next day baking",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Mix ingredients",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Follow specific bread recipe",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Let it rest 30 minutes",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Allow dough to rest and rise initially",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Stretch and fold into a ball, repeat 4 times",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Every 30 mins do a stretch and fold",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Shape into a ball and let it rest 12 hours in fridge",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "12 hours",
    notes: "Overnight fermentation in the fridge",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Preheat oven and cast iron for 1 hr at 450f",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Ensure oven is at optimal temperature",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Put the bread in cast iron and score",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "40 minutes",
    notes: "Score bread for aesthetic and practical baking reasons",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Bake extra 10-20 minutes until golden brown",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "20 minutes",
    notes: "Final bake to achieve crust color and texture",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Let it cool for 1 hour",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Cool on a wire rack to maintain crust texture",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy tickets for Met Museum",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Purchase online to avoid queues",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy tickets for WTC Sky View",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Check for weather conditions before booking",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Make reservations for Peter Luger",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "20 minutes",
    notes: "Book well in advance due to popularity",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy tickets for NY Yankees",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "20 minutes",
    notes: "Select optimal game and seating",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Decide what Broadway show to watch and buy tickets",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Choose based on reviews and availability",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Make hotel reservations",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "25 minutes",
    notes: "Compare rates and locations in Manhattan",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Make flight reservations",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Book flights aligning with travel dates",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "See climate to choose proper clothing",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Check weather forecast week before packing",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Highlight good restaurants around Central Park",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Look for variety and top-rated spots",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "List of best sushi bars in town",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Research and note down top-rated sushi bars",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy picnic basket",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Choose a large enough basket for all food items",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy sunscreen",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "SPF 50+ recommended",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy cured meats, cheeses, artisan bread and wine and sodas",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Select a variety to cater to all tastes",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Check if partner has bicycle ready",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Ensure both bicycles are in good condition",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Check my bicycle",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Perform basic maintenance if necessary",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Check climate",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Plan for weather-appropriate clothing and items",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Prepare backpack with sunglasses, cards, keys",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Pack all essentials for a day out",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Take all of my clothes out",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Pile clothes on the bed to see everything",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Process clothes to see if they spark joy or they go",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Decide which clothes to keep",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Put clothes where they belong",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Organize clothes back into closet neatly",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Take all books out",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Gather all books from around the house",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Process books",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Decide which books to keep",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Put books where they belong",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Reorganize books on shelves",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Take all miscellaneous things out",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Sort through miscellaneous items",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Process them",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Determine what to keep or discard",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Put the miscellaneous items where they belong",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Organize items neatly in their places",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Take all sentimental value items out",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Handle with care, lay out items to view",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Process them",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Decide what is truly valuable and what can be let go",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Take them back where they belong",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Store sentimental items in a respectful place",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Turn bright lights off 2 hours before bed",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Prepares body for sleep by reducing light exposure",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Relax by doing a calm activity like reading, stretching",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Helps decrease stress and relax the body",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Prepare chamomile tea",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Chamomile is known for its calming effects",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Prepare aromatherapy with lavender",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Lavender helps in reducing sleep anxiety",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Get into comfy clothes",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Comfortable clothing aids better sleep",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Get a glass of water for when you wake up",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 minutes",
    notes: "Staying hydrated is important after a night's sleep",
    files: "",
  },
  {
    id: null,
    listID: null,
    description:
      "Meditate or listen to ASMR recordings to help you fall asleep",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Meditation or ASMR can significantly improve sleep quality",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Update CV",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Keep your professional information up to date",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Update LinkedIn profile",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Important for maintaining a professional online presence",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Research companies that hire people in your position",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Understand potential employers and the job market",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Apply to job offers",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "3 hours",
    notes: "The more applications you submit, the better your chances",
    files: "",
  },
  {
    id: null,
    listID: null,
    description:
      "Prepare by asking a friend to interview you and give you feedback",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes:
      "Mock interviews can greatly improve your real interview performance",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Check dressing options to give the best impression",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Proper attire is crucial for a positive first impression",
    files: "",
  },
  {
    id: null,
    listID: null,
    description:
      "Be patient, it takes time and don't take it personal, rinse and repeat as necessary",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "Ongoing",
    notes: "Job hunting is a marathon, not a sprint",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Invite friends",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "20 minutes",
    notes: "Gather your fellow LOTR enthusiasts",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy movies",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Ensure you have all the films ready for the marathon",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy tons of potatoes",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Essential for the 'PO-TA-TOES' dish",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Boil 'em",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Start the cooking process for the feast",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Mash 'em",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "20 minutes",
    notes: "Prepare mashed potatoes as part of the themed meal",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Stick 'em in a stew",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Complete the iconic dish from the series",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy beer and sodas",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "30 minutes",
    notes: "Stock up on drinks for the marathon",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Get comfy clothes",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Comfort is key for a movie marathon",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Ask friends to bring other LOTR themed food",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "20 minutes",
    notes: "Make it a potluck with themed snacks from others",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch The Shining",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Classic psychological horror",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch Spirited Away",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Acclaimed animated fantasy film",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch Birdman",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Dramatic comedy that explores fame and relevance",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch The Godfather",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "3 hours",
    notes: "Epic mafia saga",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch Mad Max Fury Road",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Action-packed post-apocalyptic film",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch The Grand Budapest Hotel",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1.5 hours",
    notes: "Comedy-drama with visual and narrative style",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch [REC]",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1.5 hours",
    notes: "Spanish horror film with found footage style",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch Alien",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Groundbreaking sci-fi horror",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch Blade Runner 2049",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2.5 hours",
    notes: "Sequel to the sci-fi classic Blade Runner",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Watch Pan's Labyrinth",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Dark fantasy with historical context",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy coals",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Essential for grilling",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy apple wood chunks",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Adds smoky flavor to meats",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy salt",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Basic seasoning",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy pepper, all kinds",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "For seasoning meats",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy paprika",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Gives color and flavor to meats",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy cayenne",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Adds heat to dishes",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy pork butt",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "For pulled pork",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy ribs",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "15 minutes",
    notes: "Main dish for BBQ",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy lighter",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Needed to start the grill",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy foil",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Useful for cooking and storage",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy beer",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Beverages for guests",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy brioche bread",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "10 minutes",
    notes: "Goes well with BBQ",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy chips",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Snacks for the BBQ",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Buy mayo",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "5 minutes",
    notes: "Condiment for sandwiches",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Study state hook",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Learn how useState manages state in functional components",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Study effect hook",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Understand useEffect for side effects in functional components",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Study ref hook",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Explore useRef for referencing DOM elements",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Study context hook",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Use React Context API with useContext for global state",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Study reduce hook",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "1 hour",
    notes: "Learn how useReducer works for state management",
    files: "",
  },
  {
    id: null,
    listID: null,
    description: "Create custom hooks",
    done: true,
    doneByXDate: "Sun Apr 28 2024 20:11:33 GMT-0600 (Central Standard Time)",
    howMuchTimeItTakes: "2 hours",
    notes: "Develop custom hooks for reusable logic",
    files: "",
  },
];
